kind: Deployment
apiVersion: apps/v1
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: zografska/k8s-project:2.0
        ports:
        - containerPort: 3000
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: myapp-service
spec:
  type: NodePort  
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      nodePort: 30001
  selector:
    app: myapp

